theme: jekyll-theme-minimal

title: Wenda Zhao
description: Ph.D. Candidate at Dynamic System Lab (DSL), University of Toronto

Welcome! 欢迎!

logo: /Wenda.jpeg

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-redirect-from




