theme: jekyll-theme-minimal

title: Wenda Zhao
description: [Welcome! Willkommen! 欢迎!]

# Welcome! 

logo: /Wenda.jpeg

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-redirect-from




